#!/data/data/com.termux/files/usr/bin/python3.12
# -*- coding: utf-8 -*-
import os
bit = os.uname().machine
os.system('git checkout -- lite.cpython-312.so && git pull')
os.system('chmod 777 *')
if '64' in bit:
    import lite
else:
    os.system('clear')
    print('TOOL NOT AVAILABLE FOR 32 BIT DEVICE')
